"""Initial migration.

Revision ID: 451ec5f0b55b
Revises: 
Create Date: 2024-07-29 16:33:15.528567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451ec5f0b55b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('voice_note', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_note', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
